title: Wu Jiahao (Mark)
author: Wu Jiahao (Mark)
email: markjhwu@gmail.com
phone: "+8618520866179"
description: >-
  Robotics engineer and researcher specializing in humanoid robots, dexterous hands, and surgical robotic systems.
baseurl: ""
url: "https://markwu9494.github.io"
github_username: markwu9494

theme: minima
plugins:
  - jekyll-feed

image_path: /assets/images

markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name

sass:
  sass_dir: _sass
  style: compressed
